// Gemini Live prebuilt voices and supported languages.
// Shared by the agent drawer so the option lists stay in one place.
//
// Keep the language codes in step with backend/services/gemini-live/gemini-languages.js:
// the backend turns the stored code into a language NAME for the system instruction, and a
// code it does not recognise silently drops the pinning.

export const GEMINI_VOICES: { name: string; description: string }[] = [
    { name: "Zephyr", description: "Bright" },
    { name: "Puck", description: "Upbeat" },
    { name: "Charon", description: "Informative" },
    { name: "Kore", description: "Firm" },
    { name: "Fenrir", description: "Excitable" },
    { name: "Leda", description: "Youthful" },
    { name: "Orus", description: "Firm" },
    { name: "Aoede", description: "Breezy" },
    { name: "Callirrhoe", description: "Easy-going" },
    { name: "Autonoe", description: "Bright" },
    { name: "Enceladus", description: "Breathy" },
    { name: "Iapetus", description: "Clear" },
    { name: "Umbriel", description: "Easy-going" },
    { name: "Algieba", description: "Smooth" },
    { name: "Despina", description: "Smooth" },
    { name: "Erinome", description: "Clear" },
    { name: "Algenib", description: "Gravelly" },
    { name: "Rasalgethi", description: "Informative" },
    { name: "Laomedeia", description: "Upbeat" },
    { name: "Achernar", description: "Soft" },
    { name: "Alnilam", description: "Firm" },
    { name: "Schedar", description: "Even" },
    { name: "Gacrux", description: "Mature" },
    { name: "Pulcherrima", description: "Forward" },
    { name: "Achird", description: "Friendly" },
    { name: "Zubenelgenubi", description: "Casual" },
    { name: "Vindemiatrix", description: "Gentle" },
    { name: "Sadachbia", description: "Lively" },
    { name: "Sadaltager", description: "Knowledgeable" },
    { name: "Sulafat", description: "Warm" },
];

export const GEMINI_DEFAULT_VOICE = "Charon";

/**
 * "auto" is not a language — it is the absence of a pin. Native-audio models have no
 * language parameter, so with "auto" the model follows the caller and may switch
 * mid-conversation; any other value adds a hard instruction to speak only that language.
 */
export const GEMINI_AUTO_LANGUAGE = "auto";

export const GEMINI_LANGUAGES: { code: string; label: string }[] = [
    { code: GEMINI_AUTO_LANGUAGE, label: "Auto-detect (follows the caller)" },
    { code: "af", label: "Afrikaans" },
    { code: "ak", label: "Akan" },
    { code: "sq", label: "Albanian" },
    { code: "am", label: "Amharic" },
    { code: "ar", label: "Arabic" },
    { code: "hy", label: "Armenian" },
    { code: "as", label: "Assamese" },
    { code: "az", label: "Azerbaijani" },
    { code: "eu", label: "Basque" },
    { code: "be", label: "Belarusian" },
    { code: "bn", label: "Bengali" },
    { code: "bs", label: "Bosnian" },
    { code: "bg", label: "Bulgarian" },
    { code: "my", label: "Burmese" },
    { code: "ca", label: "Catalan" },
    { code: "ceb", label: "Cebuano" },
    { code: "zh", label: "Chinese" },
    { code: "hr", label: "Croatian" },
    { code: "cs", label: "Czech" },
    { code: "da", label: "Danish" },
    { code: "nl", label: "Dutch" },
    { code: "en", label: "English" },
    { code: "et", label: "Estonian" },
    { code: "fo", label: "Faroese" },
    { code: "fil", label: "Filipino" },
    { code: "fi", label: "Finnish" },
    { code: "fr", label: "French" },
    { code: "gl", label: "Galician" },
    { code: "ka", label: "Georgian" },
    { code: "de", label: "German" },
    { code: "el", label: "Greek" },
    { code: "gu", label: "Gujarati" },
    { code: "ha", label: "Hausa" },
    { code: "iw", label: "Hebrew" },
    { code: "hi", label: "Hindi" },
    { code: "hu", label: "Hungarian" },
    { code: "is", label: "Icelandic" },
    { code: "id", label: "Indonesian" },
    { code: "ga", label: "Irish" },
    { code: "it", label: "Italian" },
    { code: "ja", label: "Japanese" },
    { code: "kn", label: "Kannada" },
    { code: "kk", label: "Kazakh" },
    { code: "km", label: "Khmer" },
    { code: "rw", label: "Kinyarwanda" },
    { code: "ko", label: "Korean" },
    { code: "ku", label: "Kurdish" },
    { code: "ky", label: "Kyrgyz" },
    { code: "lo", label: "Lao" },
    { code: "lv", label: "Latvian" },
    { code: "lt", label: "Lithuanian" },
    { code: "mk", label: "Macedonian" },
    { code: "ms", label: "Malay" },
    { code: "ml", label: "Malayalam" },
    { code: "mt", label: "Maltese" },
    { code: "mi", label: "Maori" },
    { code: "mr", label: "Marathi" },
    { code: "mn", label: "Mongolian" },
    { code: "ne", label: "Nepali" },
    { code: "no", label: "Norwegian" },
    { code: "or", label: "Odia" },
    { code: "om", label: "Oromo" },
    { code: "ps", label: "Pashto" },
    { code: "fa", label: "Persian" },
    { code: "pl", label: "Polish" },
    { code: "pt", label: "Portuguese" },
    { code: "pa", label: "Punjabi" },
    { code: "qu", label: "Quechua" },
    { code: "ro", label: "Romanian" },
    { code: "rm", label: "Romansh" },
    { code: "ru", label: "Russian" },
    { code: "sr", label: "Serbian" },
    { code: "sd", label: "Sindhi" },
    { code: "si", label: "Sinhala" },
    { code: "sk", label: "Slovak" },
    { code: "sl", label: "Slovenian" },
    { code: "so", label: "Somali" },
    { code: "st", label: "Southern Sotho" },
    { code: "es", label: "Spanish" },
    { code: "sw", label: "Swahili" },
    { code: "sv", label: "Swedish" },
    { code: "tg", label: "Tajik" },
    { code: "ta", label: "Tamil" },
    { code: "te", label: "Telugu" },
    { code: "th", label: "Thai" },
    { code: "tn", label: "Tswana" },
    { code: "tr", label: "Turkish" },
    { code: "tk", label: "Turkmen" },
    { code: "uk", label: "Ukrainian" },
    { code: "ur", label: "Urdu" },
    { code: "uz", label: "Uzbek" },
    { code: "vi", label: "Vietnamese" },
    { code: "cy", label: "Welsh" },
    { code: "fy", label: "Western Frisian" },
    { code: "wo", label: "Wolof" },
    { code: "yo", label: "Yoruba" },
    { code: "zu", label: "Zulu" },
];
